import { FollowUpQuestion, UserProfile } from '../types';

export const FOLLOW_UP_QUESTIONS: Record<keyof UserProfile, FollowUpQuestion> = {
  gender: {
    field: 'gender',
    question_en: 'What is your gender?',
    question_hi: 'आपका लिंग क्या है?',
    options: [
      { label_en: 'Woman / Female', label_hi: 'महिला / औरत', value: 'female' },
      { label_en: 'Man / Male', label_hi: 'पुरुष / आदमी', value: 'male' },
      { label_en: 'Transgender', label_hi: 'ट्रांसजेंडर', value: 'transgender' },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: 'any' },
    ],
  },
  caste_category: {
    field: 'caste_category',
    question_en: 'Which social category do you belong to? (Many special benefits are reserved for specific categories)',
    question_hi: 'आप किस सामाजिक श्रेणी (जाति वर्ग) से संबंधित हैं? (कई विशेष सरकारी योजनाएं आरक्षित हैं)',
    options: [
      { label_en: 'SC (Scheduled Caste)', label_hi: 'SC (अनुसूचित जाति)', value: 'sc' },
      { label_en: 'ST (Scheduled Tribe)', label_hi: 'ST (अनुसूचित जनजाति)', value: 'st' },
      { label_en: 'OBC (Other Backward Class)', label_hi: 'OBC (अन्य पिछड़ा वर्ग)', value: 'obc' },
      { label_en: 'Minority (Muslim, Sikh, Christian, Jain, Buddhist, Parsi)', label_hi: 'अल्पसंख्यक (मुस्लिम, सिख, ईसाई, जैन, बौद्ध)', value: 'minority' },
      { label_en: 'General / EWS', label_hi: 'सामान्य (General) / EWS', value: 'general' },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: 'any' },
    ],
  },
  district_type: {
    field: 'district_type',
    question_en: 'Where is your business located?',
    question_hi: 'आपका व्यवसाय किस क्षेत्र में स्थित है?',
    options: [
      { label_en: 'Rural (Village / Gaon)', label_hi: 'ग्रामीण (गांव / देहात)', value: 'rural' },
      { label_en: 'Urban (City / Metro)', label_hi: 'शहरी (शहर / नगर)', value: 'urban' },
      { label_en: 'Semi-Urban (Town / Kasba)', label_hi: 'कस्बा / अर्ध-शहरी (Town)', value: 'semi-urban' },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: 'any' },
    ],
  },
  business_type: {
    field: 'business_type',
    question_en: 'What type of business or trade are you running or planning?',
    question_hi: 'आप किस प्रकार का व्यवसाय या काम कर रहे हैं या शुरू करना चाहते हैं?',
    options: [
      { label_en: 'Tailoring, Artisan & Handicrafts', label_hi: 'सिलाई, कारीगरी, हस्तशिल्प', value: 'artisan_handicraft' },
      { label_en: 'Small Shop / Retail (Kirana, etc.)', label_hi: 'छोटी दुकान / किराना / रिटेल', value: 'retail_shop' },
      { label_en: 'Street Vendor / Cart / Stall', label_hi: 'ठेला / रेहड़ी-पटरी विक्रेता', value: 'street_vendor' },
      { label_en: 'Dairy, Cattle & Animal Husbandry', label_hi: 'डेयरी, पशुपालन व दूध उत्पादन', value: 'dairy_livestock' },
      { label_en: 'Weaving & Handloom / Textiles', label_hi: 'बुनकर / हथकरघा / कपड़ा कार्य', value: 'textile_weaving' },
      { label_en: 'Fisheries & Aquaculture', label_hi: 'मछली पालन व जलीय कृषि', value: 'fisheries' },
      { label_en: 'Food Processing / Bakery / Snacks', label_hi: 'खाद्य प्रसंस्करण / बेकरी / नमकीन', value: 'food_processing' },
      { label_en: 'Manufacturing & Small Factory', label_hi: 'विनिर्माण / छोटा कारखाना', value: 'manufacturing' },
      { label_en: 'Services (Repair, Salon, Clinic)', label_hi: 'सेवा क्षेत्र (मरम्मत, सैलून, आदि)', value: 'services' },
      { label_en: 'Tech Startup / Innovation', label_hi: 'स्टार्टअप व तकनीकी नवाचार', value: 'tech_startup' },
      { label_en: 'Other / Not Decided Yet', label_hi: 'अन्य / अभी तय नहीं किया', value: 'any' },
    ],
  },
  age: {
    field: 'age',
    question_en: 'What is your age bracket?',
    question_hi: 'आपकी आयु वर्ग क्या है?',
    options: [
      { label_en: '18 - 35 years (Youth)', label_hi: '18 - 35 वर्ष (युवा)', value: 25 },
      { label_en: '36 - 55 years', label_hi: '36 - 55 वर्ष', value: 45 },
      { label_en: '56+ years', label_hi: '56+ वर्ष', value: 60 },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: null },
    ],
  },
  estimated_income: {
    field: 'estimated_income',
    question_en: 'What is your family\'s approximate annual income?',
    question_hi: 'आपके परिवार की वार्षिक आय लगभग कितनी है?',
    options: [
      { label_en: 'Under ₹1.5 Lakh / year (BPL/Low)', label_hi: '₹1.5 लाख से कम (कम आय)', value: 120000 },
      { label_en: '₹1.5 Lakh to ₹3 Lakh / year', label_hi: '₹1.5 लाख से ₹3 लाख / वर्ष', value: 240000 },
      { label_en: 'Above ₹3 Lakh / year', label_hi: '₹3 लाख से अधिक', value: 450000 },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: null },
    ],
  },
  state: {
    field: 'state',
    question_en: 'Which State/UT are you located in?',
    question_hi: 'आप किस राज्य / केंद्र शासित प्रदेश में हैं?',
    options: [
      { label_en: 'Uttar Pradesh', label_hi: 'उत्तर प्रदेश', value: 'Uttar Pradesh' },
      { label_en: 'Bihar', label_hi: 'बिहार', value: 'Bihar' },
      { label_en: 'Rajasthan', label_hi: 'राजस्थान', value: 'Rajasthan' },
      { label_en: 'Madhya Pradesh', label_hi: 'मध्य प्रदेश', value: 'Madhya Pradesh' },
      { label_en: 'Maharashtra', label_hi: 'महाराष्ट्र', value: 'Maharashtra' },
      { label_en: 'Delhi / NCR', label_hi: 'दिल्ली / एनसीआर', value: 'Delhi' },
      { label_en: 'Other State / All India', label_hi: 'अन्य राज्य / संपूर्ण भारत', value: null },
    ],
  },
  is_differently_abled: {
    field: 'is_differently_abled',
    question_en: 'Are you a differently-abled person (Divyangjan)?',
    question_hi: 'क्या आप दिव्यांगजन (विशिष्ट दिव्यांग) हैं?',
    options: [
      { label_en: 'Yes (Divyangjan)', label_hi: 'हाँ (दिव्यांगजन)', value: true },
      { label_en: 'No', label_hi: 'नहीं', value: false },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: null },
    ],
  },
  education_level: {
    field: 'education_level',
    question_en: 'What is your current education level?',
    question_hi: 'आपका वर्तमान शिक्षा स्तर क्या है?',
    options: [
      { label_en: 'School (Class 8th - 12th)', label_hi: 'स्कूल (कक्षा 8वीं - 12वीं)', value: 'school' },
      { label_en: 'Undergraduate College (BA, BSc, BTech, etc.)', label_hi: 'स्नातक / कॉलेज (UG - BA, BSc, BTech)', value: 'undergraduate' },
      { label_en: 'Postgraduate (MA, MSc, MTech, MBA, etc.)', label_hi: 'स्नातकोत्तर (PG - MA, MSc, MTech)', value: 'postgraduate' },
      { label_en: 'Diploma / Polytechnic / ITI', label_hi: 'डिप्लोमा / पॉलिटेक्निक / आईटीआई', value: 'diploma' },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: 'any' },
    ],
  },
  current_marks_percentage: {
    field: 'current_marks_percentage',
    question_en: 'What was your approximate marks percentage in your last qualifying exam?',
    question_hi: 'आपकी पिछली परीक्षा में लगभग कितने प्रतिशत अंक थे?',
    options: [
      { label_en: 'Above 80% (High Merit)', label_hi: '80% से अधिक (उच्च मेरिट)', value: 85 },
      { label_en: '60% to 80% (First Division)', label_hi: '60% से 80% (प्रथम श्रेणी)', value: 70 },
      { label_en: '50% to 60%', label_hi: '50% से 60%', value: 55 },
      { label_en: 'Below 50%', label_hi: '50% से कम', value: 45 },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: null },
    ],
  },
  course_type: {
    field: 'course_type',
    question_en: 'What type of course or stream are you pursuing?',
    question_hi: 'आप किस प्रकार का कोर्स या स्ट्रीम पढ़ रहे हैं?',
    options: [
      { label_en: 'Technical / Engineering', label_hi: 'तकनीकी / इंजीनियरिंग', value: 'technical' },
      { label_en: 'General (Arts, Science, Commerce)', label_hi: 'सामान्य (कला, विज्ञान, वाणिज्य)', value: 'general' },
      { label_en: 'Medical / Healthcare / Pharma', label_hi: 'चिकित्सा / मेडिकल / फार्मा', value: 'medical' },
      { label_en: 'Vocational / ITI / Skill Course', label_hi: 'व्यावसायिक / आईटीआई', value: 'vocational' },
      { label_en: 'Prefer not to say', label_hi: 'नहीं बताना चाहते', value: 'any' },
    ],
  },
};
